language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle
install:
  - pip install html5validator
# command to run tests
script:
  - html5validator --root .
